### ISSUE TITLE
Segfault with OCaml 5.2

### ISSUE THREAD

**Issue by kit-ty-kate** [kayceesrk/delimcc_of_fxhandler#1]
The tests of delimcc_of_fxhandler currently fails with a segfault on OCaml 5.2 (but works fine on OCaml 5.1):
```
#=== ERROR while compiling delimcc_of_fxhandler.0.1 ===========================#
# context              2.2.0~beta2~dev | linux/x86_64 | ocaml-variants.5.2.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.2/.opam-switch/build/delimcc_of_fxhandler.0.1
# command              ~/.opam/5.2/bin/dune build -p delimcc_of_fxhandler -j 1 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/delimcc_of_fxhandler-126-30dc42.env
# output-file          ~/.opam/log/delimcc_of_fxhandler-126-30dc42.out
### output ###
# File "test/dune", line 2, characters 7-12:
# 2 |  (name test1)
#            ^^^^^
# (cd _build/default/test && ./test1.exe)
# Command got signal SEGV.
```
This may be a compiler bug as I'm not seeing any warning due to a change in the C API when compiling multicont (cc @dhil) but if any of you two know where this could come from that would be a huge help. In the meantime i'll try to debug this further.

**Comment by dhil** [comment]
I think this is a problem with the multicont package on OCaml 5.2.0. All my examples multicont programs segfaults on OCaml 5.2.0, but works on OCaml 5.1.1.

**Comment by dhil** [comment]
I have initiated a new release of multicont with support for OCaml 5.2.

**Comment by dhil** [comment]
Earlier today multicont version 1.0.2 was released. It should resolve this issue.

**Comment by kit-ty-kate** [comment]
I can confirm. Thank you so much!
